// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZl_t9LIM1ddo7jKcZfDc1nMJGbclIgT4',
    appId: '1:60044014899:web:ced97f1da19fa1e3c77a46',
    messagingSenderId: '60044014899',
    projectId: 'mood-menders-bb1e3',
    authDomain: 'mood-menders-bb1e3.firebaseapp.com',
    storageBucket: 'mood-menders-bb1e3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV0E_zAuPxlgk5WOXHKse-ve-jZQ2Ov-E',
    appId: '1:60044014899:android:008c5436b491c6c7c77a46',
    messagingSenderId: '60044014899',
    projectId: 'mood-menders-bb1e3',
    storageBucket: 'mood-menders-bb1e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANR06mxS5v0tQxbOynTvnSWhoBTNu9Rdg',
    appId: '1:60044014899:ios:86ee1bd7ff4559b7c77a46',
    messagingSenderId: '60044014899',
    projectId: 'mood-menders-bb1e3',
    storageBucket: 'mood-menders-bb1e3.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANR06mxS5v0tQxbOynTvnSWhoBTNu9Rdg',
    appId: '1:60044014899:ios:9963745e8a7d0b78c77a46',
    messagingSenderId: '60044014899',
    projectId: 'mood-menders-bb1e3',
    storageBucket: 'mood-menders-bb1e3.appspot.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
